priority_files:
  - "README.md"
  - "README.txt"
  - "pyproject.toml"
  - "requirements.txt"
  - "package.json"
  - "Dockerfile"
  - "docker-compose.yml"
  - "docker-compose.yaml"
  - "serverless.yml"
  - ".env.example"
  - "Makefile"
  - "Procfile"
  - "netlify.toml"
  - "vercel.json"